title: Intorudction to Digital Humanities
email: deanna.stover@cnu.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is the Fall 2020 syllabus for IDST 270: Introduction to Digital Humanities.  
  This syllabus may be freely reused with attribution. 
baseurl: "/courses/new/master/fall2020/idst270" # the subpath of your site, e.g. /blog
url: "localhost4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: deannaMFstover
github_username:  deanna-stover

# Build settings
markdown: kramdown
toc_depth: 1
theme: minima
plugins:
  - jekyll-feed
