---
title: "Deanna Stover's Courses"
url: "https://deanna-stover.github.io/coursesCNU"
baseurl: ""
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Readme.md
  - _scripts/

theme: jekyll-theme-minimal
logo: /images/PenNib.png
