---
title: "Deanna Stover's Courses"
url: "https://github.com/deanna-stover"
baseurl: "/courses-trial"
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Readme.md
  - _scripts/
