---
title: "Deanna Stover's Courses"
description: Deanna Stover is an Assistant Professor at Christopher Newport University. This website is a compilation of her syllabi since starting at CNU in Fall 2020. Anything on this site can be used freely with attribution. 
url: "https://deanna-stover.github.io"
baseurl: "/coursesCNU"
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Readme.md
  - _scripts/

theme: jekyll-theme-minimal
logo: /images/PenNib.png
